[package]
name = "imageproc"
version = "0.23.0"
authors = ["theotherphil"]
edition = "2018"
license = "MIT"
description = "Image processing operations"
readme = "README.md"
repository = "https://github.com/image-rs/imageproc.git"
homepage = "https://github.com/image-rs/imageproc"
exclude = ["examples/*.ttf"]

[features]
default = [ "rayon", "std" ]
property-testing = [ "quickcheck" ]
display-window = ["sdl2"]
sgx = ["image/sgx", "sgx_tstd"]
std = ["image/std"]

[dependencies]
approx = "0.5"
conv = "0.3.3"
image = { version = "0.24.1", default-features = false }
itertools = { version = "0.10.0", default-features = false, features = ["use_alloc"] }
nalgebra = { version = "0.30", default-features = false, features = ["std"] }
num = "0.4"
rand = "0.7.3"
rand_distr = "0.2.2"
rusttype = "0.9.2"
rayon = { version = "1.5.1", optional = true }
quickcheck = { version = "0.9.2", optional = true }
sdl2 = { version = "0.35", optional = true, default-features = false, features = ["bundled"] }

sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
assert_approx_eq = "1.1.0"
image = "0.24.1"
quickcheck = "0.9.2"
wasm-bindgen-test = "0.3.14"

[package.metadata.docs.rs]
# See https://github.com/image-rs/imageproc/issues/358
# all-features = true
features = [ "property-testing" ]

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
