[package]
name = "imageproc"
version = "0.23.0"
authors = ["theotherphil"]
edition = "2018"
license = "MIT"
description = "Image processing operations"
readme = "README.md"
repository = "https://github.com/image-rs/imageproc.git"
homepage = "https://github.com/image-rs/imageproc"
exclude = ["examples/*.ttf"]

[features]
default = [ "rayon", "std" ]
property-testing = [ "quickcheck" ]
display-window = ["sdl2"]
# libm: "Uncomment if you wish to use `Float` and `Real` without `std`"
libm = ["nalgebra/libm", "num-traits/libm", "num/libm", "rusttype/libm-math"]
sgx = ["image/sgx", "sgx_tstd", "rand/getrandom", "libm"]
std = ["image/std", "rusttype/std", "rand/std", "rand_core/getrandom"]

[dependencies]
approx = { version = "0.5", default-features = false }
image = { version = "0.24.1", default-features = false }
itertools = { version = "0.10.0", default-features = false, features = ["use_alloc"] }
nalgebra = { version = "0.30", default-features = false }
num-traits = { version = "0.2", default-features = false }
num = { version = "0.4", default-features = false, features = ["alloc"] }
rand = { version = "0.8.5", default-features = false }
rand_core = {  version = "0.6.4", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
rand_distr = { version = "0.4.3", default-features = false, features = ["alloc"] }
rusttype = { version = "0.9.3", default-features = false }
rayon = { version = "1.5.1", optional = true }
quickcheck = { version = "0.9.2", optional = true }
sdl2 = { version = "0.35", optional = true, default-features = false, features = ["bundled"] }

sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
assert_approx_eq = "1.1.0"
image = "0.24.1"
quickcheck = "0.9.2"
wasm-bindgen-test = "0.3.14"

# TODO(interstellar) remove patch
[patch.crates-io]
image = { path = "../../../../image" }

[package.metadata.docs.rs]
# See https://github.com/image-rs/imageproc/issues/358
# all-features = true
features = [ "property-testing" ]

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
